# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Matthew Jones
tagline:          '@metamattj on software and data'
description:      'Director of Informatics Research and Development at <a href="http://www.nceas.ucsb.edu" target="_blank">NCEAS</a>.'
url:              http://matt.magisa.org

author:
  name:           'Matt Jones'
  url:            https://matt.magisa.org

paginate:         5

# Custom vars
version:          2.0.0

twitter:
  url:           https://twitter.com/metamattj

github:
  repo:           https://github.com/mbjones
