# Dependencies

# Gems
gems:             [jekyll/scholar, jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Matthew Jones
tagline:          '@metamattj on software and data'
description:      '<a href="https://www.nceas.ucsb.edu/content/matt-jones-director-informatics-research-and-development">Director of Informatics Research and Development</a> at <a href="http://www.nceas.ucsb.edu" target="_blank">NCEAS</a>.'
url:              http://matt.magisa.org

author:
  name:           'Matt Jones'
  email:          'jones@nceas.ucsb.edu'
  url:            https://matt.magisa.org

paginate:         5

# Custom vars
version:          2.0.0

twitter:
  nick:           '@metamattj'
  url:            https://twitter.com/metamattj

github:
  user:           'mbjones'
  url:            https://github.com/mbjones

orcid:
  id:             0000-0003-0077-4738
  url:            http://orcid.org/0000-0003-0077-4738

impact:
  id:             MatthewBJones
  url:            https://impactstory.org/u/0000-0003-0077-4738

keybase:
  id:             mbjones
  url:            https://keybase.io/mbjones

# Jekyll scholar
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: mbjones.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

