# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Matthew Jones
tagline:          '@metamattj on software and data'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://matt.magisa.org

author:
  name:           'Matt Jones'
  url:            https://matt.magisa.org

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/mbjones
